### ISSUE TITLE
how to you work with two data loaders?

### ISSUE THREAD

**Issue by shamanez** [vfdev-5/UDA-pytorch#2]
Since there are two datasets of labeled and unlabeled in different amounts, how do you calculate the epochs, is it for labeled data only ? if yes how do u use all the unlabeled examples?

**Comment by vfdev-5** [comment]
> how do you calculate the epochs, is it for labeled data only ?

yes
https://github.com/vfdev-5/UDA-pytorch/blob/740a6740eab29f9b916ffa62c9baf4bec092c0d2/code/main.py#L263

> if yes how do u use all the unlabeled examples?

Just iterate over data while the training iterations

https://github.com/vfdev-5/UDA-pytorch/blob/740a6740eab29f9b916ffa62c9baf4bec092c0d2/code/main.py#L94-L99

https://github.com/vfdev-5/UDA-pytorch/blob/740a6740eab29f9b916ffa62c9baf4bec092c0d2/code/main.py#L115

**Comment by vfdev-5** [comment]
Closed issue as answered
